language: node_js
node_js:
    - "10.16.0"

before_script:
    - npm install -g @angular/cli
script:
    - echo Test Building Prod Build
    - ng build --aot --prod
    - echo Running tests
    - npm run test:headless 
